"""initial schema

Revision ID: 897dc46683ea
Revises: 
Create Date: 2026-09-07 16:27:41.820913+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import nirikshan.models.base  # noqa: F401 - referenced by UTCDateTime columns below


revision: str = '897dc46683ea'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_at', ['at'], unique=False)
        batch_op.create_index('ix_audit_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('historical_incidents',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('incident_ref', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('resolved_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=60), nullable=False),
    sa.Column('doc_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    with op.batch_alter_table('historical_incidents', schema=None) as batch_op:
        batch_op.create_index('ix_hist_service', ['service_name'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('prompt_versions',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_name_version', ['name', 'version'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('environments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_env_org_name')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_organization_id'), ['organization_id'], unique=False)

    op.create_table('services',
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('owner_team', sa.String(length=120), nullable=False),
    sa.Column('runbook_url', sa.String(length=400), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('health_updated_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('slo_latency_ms_p95', sa.Float(), nullable=False),
    sa.Column('slo_error_rate', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'name', name='uq_service_env_name')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=False)

    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('signal_kind', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('comparison', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('for_seconds', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('breaching_since', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('active_alert_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_service_id'), ['service_id'], unique=False)

    op.create_table('anomalies',
    sa.Column('detected_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_low', sa.Float(), nullable=False),
    sa.Column('expected_high', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_anomaly_service_metric_ts', ['service_id', 'metric_name', 'detected_at'], unique=False)

    op.create_table('deployments',
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('previous_version', sa.String(length=60), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('started_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=120), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index('ix_deploy_service_started', ['service_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_service_id'), ['service_id'], unique=False)

    op.create_table('incidents',
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('detected_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('mitigated_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('blast_radius', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=80), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('correlated_alert_refs', sa.JSON(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('last_investigation_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incident_dedup', ['dedup_key'], unique=False)
        batch_op.create_index('ix_incident_service_detected', ['service_id', 'detected_at'], unique=False)
        batch_op.create_index('ix_incident_status_sev', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_dedup_key'), ['dedup_key'], unique=False)

    op.create_table('metric_baselines',
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('ewma', sa.Float(), nullable=False),
    sa.Column('ewvar', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_from_ts', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_baselines', schema=None) as batch_op:
        batch_op.create_index('ix_baseline_key', ['service_id', 'metric_name'], unique=True)

    op.create_table('service_dependencies',
    sa.Column('upstream_id', sa.String(length=36), nullable=False),
    sa.Column('downstream_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['downstream_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upstream_id', 'downstream_id', name='uq_dep_pair')
    )
    with op.batch_alter_table('service_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_dependencies_downstream_id'), ['downstream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_dependencies_upstream_id'), ['upstream_id'], unique=False)

    op.create_table('service_instances',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('zone', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'host', name='uq_instance_service_host')
    )
    with op.batch_alter_table('service_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_instances_service_id'), ['service_id'], unique=False)

    op.create_table('telemetry_logs',
    sa.Column('ts', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('span_id', sa.String(length=32), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('deployment_id', sa.String(length=36), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_env_ts', ['environment_id', 'ts'], unique=False)
        batch_op.create_index('ix_logs_level_ts', ['level', 'ts'], unique=False)
        batch_op.create_index('ix_logs_service_ts', ['service_id', 'ts'], unique=False)
        batch_op.create_index('ix_logs_trace', ['trace_id'], unique=False)

    op.create_table('telemetry_metrics',
    sa.Column('ts', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_metrics_lookup', ['service_id', 'metric_name', 'ts'], unique=False)
        batch_op.create_index('ix_metrics_name_ts', ['metric_name', 'ts'], unique=False)

    op.create_table('telemetry_traces',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('root_service_id', sa.String(length=36), nullable=True),
    sa.Column('root_operation', sa.String(length=200), nullable=False),
    sa.Column('started_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('span_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('ingested_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['root_service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_traces_trace_id'), ['trace_id'], unique=True)
        batch_op.create_index('ix_traces_root_ts', ['root_service_id', 'started_at'], unique=False)

    op.create_table('trace_spans',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('parent_span_id', sa.String(length=32), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('operation', sa.String(length=200), nullable=False),
    sa.Column('started_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trace_spans', schema=None) as batch_op:
        batch_op.create_index('ix_spans_service_ts', ['service_id', 'started_at'], unique=False)
        batch_op.create_index('ix_spans_trace', ['trace_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('prompt_name', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('started_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index('ix_agent_runs_incident', ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_agent_runs_kind_status', ['kind', 'status'], unique=False)

    op.create_table('alerts',
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('signal_kind', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('fired_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('anomaly_id', sa.String(length=36), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_alerts_fired_at', ['fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_service_id'), ['service_id'], unique=False)
        batch_op.create_index('ix_alerts_state_service', ['state', 'service_id'], unique=False)

    op.create_table('incident_events',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index('ix_incident_events_incident_at', ['incident_id', 'at'], unique=False)

    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('observed_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('collected_by', sa.String(length=48), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_incident_kind', ['incident_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_evidence_run_id'), ['run_id'], unique=False)

    op.create_table('incident_hypotheses',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_hypotheses', schema=None) as batch_op:
        batch_op.create_index('ix_hypo_incident_rank', ['incident_id', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_hypotheses_run_id'), ['run_id'], unique=False)

    op.create_table('remediation_actions',
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_by_run_id', sa.String(length=36), nullable=True),
    sa.Column('action_name', sa.String(length=60), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk', sa.String(length=8), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=False),
    sa.Column('verification_plan', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('policy_findings', sa.JSON(), nullable=False),
    sa.Column('is_reversible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', nirikshan.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_actions_proposed_by_run_id'), ['proposed_by_run_id'], unique=False)
        batch_op.create_index('ix_remediation_incident_status', ['incident_id', 'status'], unique=False)

    op.create_table('agent_tool_calls',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=60), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('result_rows', sa.Integer(), nullable=False),
    sa.Column('started_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tool_calls', schema=None) as batch_op:
        batch_op.create_index('ix_tool_calls_run_seq', ['agent_run_id', 'sequence'], unique=False)

    op.create_table('llm_calls',
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_llm_calls_run', ['agent_run_id'], unique=False)

    op.create_table('remediation_approvals',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['remediation_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_executions',
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('started_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=False),
    sa.Column('after_state', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('created_at', nirikshan.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['remediation_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediation_executions')
    op.drop_table('remediation_approvals')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_calls_run')
        batch_op.drop_index(batch_op.f('ix_llm_calls_incident_id'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('agent_tool_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_calls_run_seq')

    op.drop_table('agent_tool_calls')
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_remediation_incident_status')
        batch_op.drop_index(batch_op.f('ix_remediation_actions_proposed_by_run_id'))

    op.drop_table('remediation_actions')
    with op.batch_alter_table('incident_hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_hypotheses_run_id'))
        batch_op.drop_index('ix_hypo_incident_rank')

    op.drop_table('incident_hypotheses')
    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_evidence_run_id'))
        batch_op.drop_index('ix_evidence_incident_kind')

    op.drop_table('incident_evidence')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_events_incident_at')

    op.drop_table('incident_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_state_service')
        batch_op.drop_index(batch_op.f('ix_alerts_service_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index('ix_alerts_fired_at')
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))

    op.drop_table('alerts')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_runs_kind_status')
        batch_op.drop_index(batch_op.f('ix_agent_runs_incident_id'))
        batch_op.drop_index('ix_agent_runs_incident')

    op.drop_table('agent_runs')
    with op.batch_alter_table('trace_spans', schema=None) as batch_op:
        batch_op.drop_index('ix_spans_trace')
        batch_op.drop_index('ix_spans_service_ts')

    op.drop_table('trace_spans')
    with op.batch_alter_table('telemetry_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_traces_root_ts')
        batch_op.drop_index(batch_op.f('ix_telemetry_traces_trace_id'))

    op.drop_table('telemetry_traces')
    with op.batch_alter_table('telemetry_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_name_ts')
        batch_op.drop_index('ix_metrics_lookup')

    op.drop_table('telemetry_metrics')
    with op.batch_alter_table('telemetry_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_trace')
        batch_op.drop_index('ix_logs_service_ts')
        batch_op.drop_index('ix_logs_level_ts')
        batch_op.drop_index('ix_logs_env_ts')

    op.drop_table('telemetry_logs')
    with op.batch_alter_table('service_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_instances_service_id'))

    op.drop_table('service_instances')
    with op.batch_alter_table('service_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_dependencies_upstream_id'))
        batch_op.drop_index(batch_op.f('ix_service_dependencies_downstream_id'))

    op.drop_table('service_dependencies')
    with op.batch_alter_table('metric_baselines', schema=None) as batch_op:
        batch_op.drop_index('ix_baseline_key')

    op.drop_table('metric_baselines')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_dedup_key'))
        batch_op.drop_index('ix_incident_status_sev')
        batch_op.drop_index('ix_incident_service_detected')
        batch_op.drop_index('ix_incident_dedup')

    op.drop_table('incidents')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_service_id'))
        batch_op.drop_index('ix_deploy_service_started')

    op.drop_table('deployments')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anomaly_service_metric_ts')

    op.drop_table('anomalies')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_service_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_name'))
        batch_op.drop_index(batch_op.f('ix_services_environment_id'))

    op.drop_table('services')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_organization_id'))

    op.drop_table('environments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_name_version')

    op.drop_table('prompt_versions')
    op.drop_table('organizations')
    with op.batch_alter_table('historical_incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_hist_service')

    op.drop_table('historical_incidents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_resource')
        batch_op.drop_index('ix_audit_at')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
